# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  warn:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - name: >-
        Emit warn on dot and -1:-1
      if: always()
      run: |
        echo "::warning file=.,line=-1,col=-1::warn on dot and -1:-1"
    - name: >-
        Emit warn on dot and 0:0
      if: always()
      run: |
        echo "::warning file=.,line=0,col=0::warn on dot and 0:0"
    - name: >-
        Emit warn on .github/workflows and 0:0
      if: always()
      run: |
        echo "::warning file=.github/workflows,line=0,col=0::warn on .github/workflows and 0:0"
    - name: >-
        Emit warn on no file and 0:0
      if: always()
      run: |
        echo "::warning line=0,col=0::warn on no file and 0:0"
    - name: Emit warn on no file and no pos
      if: always()
      run: |
        echo "::warning ::warn on no file and no pos"
    - name: Emit warn on multiword file
      if: always()
      run: |
        echo "::warning file=> > SECRET%3A INPUT PASSED TO pypa gh action pypi%2Dpublish GITHUB ACTION::warn on multiword file"
